### PR TITLE
Add compatibility with node-redis v4

### PR DESCRIPTION
**Pull request by Francois-Liveencheres**
Add compatibility with [node-redis](https://github.com/redis/node-redis) v4

Requires node v12+

### CODE REVIEW

**Review by genru — APPROVED** [review]

**Comment by OsoianMarcel** [comment]
Dear owner of the repository, would be great to accept this PR and to push a new package version on NPM registry.
Thank you.

**Comment by varad11** [comment]
IMO You should not merge this pr with master and publish it. 
Following are modifications need:
1). Cannot force it to work with only node-redis v4. It has scope to support older versions.
2). Needs backward compatibility with node-redis otherwise many projects dependent on this will have compatibility issue.

**Comment by OsoianMarcel** [comment]
@varad11 
I would merge this PR, because we need to move forward and use new software versions.
The older versions are still available as NPM package, so you are free to use them as long as you want.
But, it's up to the owner of the library.

**Comment by varad11** [comment]
@OsoianMarcel fair point, but a simple patch would cover both points I previously mentioned without much changes. I actually have opened a PR since it was a small change. The only hindrance is now the owners who seem to have stopped maintaining this module. Since a substantial number of downloads happen to this module, it seems fair that at least the pending PRs need to be addressed to make it stable and the libraries ownership needs to be transferred.

**Comment by rakeshpai** [comment]
Sorry for the delay, and thanks for the PR and the nudges. I've now published 1.0.0 (not 4.0.0) to. npm.

**Pull request merged**
